document.getElementById('info').innerText = 'This line is generated by js file';

const information = document.getElementById('info2')
information.innerText = `This app is using Chrome (v${versions.chrome()}), Node.js (v${versions.node()}), and Electron (v${versions.electron()})`

document.getElementById('btn1').click(function () {
    document.getElementById('info').style.color = 'red';
})

const func = async () => {
    const response = await window.versions.ping()
    console.log("response", response) // prints out 'pong'
}

func();
